baseurl = "https://scottcwilson.github.io/"
languageCode = "en-us"
title = "Scott C. Wilson" 
theme = "anatole"
copyright = "Scott C Wilson"
enableEmoji = true

[params]
title = "Scott C. Wilson" 
author = "Scott C. Wilson" 
description = "Mild mannered dork by day.  Even bigger dork by night."
extra_description = ["Here's some of the stuff that keeps me busy.","Mostly e-commerce, mostly Zen Cart.", "Thanks for visiting."]
profilePicture = "images/me.jpeg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/scottcwilson/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/scottcwilson" 

[[params.socialIcons]]
icon = "fa-stack-overflow"
title = "StackOverflow"
url = "https://stackoverflow.com/users/319741"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:scottcwilson@hey.com" 

[[params.socialIcons]]
icon = "fa-twitter"
title = "twitter"
url = "https://twitter.com/thatsoftwareguy"
